@echo off
REM ============================================================================
REM Tired Market - Desktop Icon Installer
REM
REM Double-click this file. It puts a "Tired Market" shortcut on your desktop
REM with the correct icon. Use that shortcut to launch every day - it has zero
REM console flash because it points pythonw.exe at the app directly.
REM
REM Safe to run multiple times - it just overwrites the desktop shortcut.
REM Works from any folder; auto-locates %USERPROFILE%\TiredMarket\.
REM ============================================================================

setlocal enabledelayedexpansion
title Tired Market - Desktop Icon Installer

echo.
echo ============================================================
echo   Tired Market - Desktop Shortcut Installer
echo ============================================================
echo.

REM 1) Locate the install dir. Prefer the folder this bat lives in (works
REM    when copied next to the app); fall back to %USERPROFILE%\TiredMarket\
REM    if invoked from a downloads folder or USB stick.
set "INSTALL_DIR=%~dp0"
if "%INSTALL_DIR:~-1%"=="\" set "INSTALL_DIR=%INSTALL_DIR:~0,-1%"

if not exist "%INSTALL_DIR%\tired_market.py" (
    if exist "%USERPROFILE%\TiredMarket\tired_market.py" (
        set "INSTALL_DIR=%USERPROFILE%\TiredMarket"
    ) else (
        echo ERROR: Could not find tired_market.py.
        echo.
        echo This installer expects the app at %USERPROFILE%\TiredMarket\ or
        echo in the same folder as this .bat file. Move it there and try
        echo again.
        echo.
        pause
        exit /b 1
    )
)

echo [1/4] Install folder:  %INSTALL_DIR%

REM 2) Confirm START.vbs is present. The shortcut targets START.vbs directly
REM    so the launch is silent (no console flash). If the file is missing
REM    (downloads that dropped .vbs, manual delete, fresh clone) we regenerate
REM    it inline rather than erroring out - the installer is self-healing.
if not exist "%INSTALL_DIR%\START.vbs" goto :create_vbs
goto :have_vbs

:create_vbs
echo START.vbs missing - regenerating it...
> "%INSTALL_DIR%\START.vbs" echo ' Tired Market - Silent Launcher ^(auto-generated by INSTALL_DESKTOP_ICON.bat^)
>> "%INSTALL_DIR%\START.vbs" echo ' Runs START.bat with a hidden window so no console box appears.
>> "%INSTALL_DIR%\START.vbs" echo Option Explicit
>> "%INSTALL_DIR%\START.vbs" echo Dim WshShell, FSO, ScriptDir, BatPath
>> "%INSTALL_DIR%\START.vbs" echo Set WshShell = CreateObject^("WScript.Shell"^)
>> "%INSTALL_DIR%\START.vbs" echo Set FSO = CreateObject^("Scripting.FileSystemObject"^)
>> "%INSTALL_DIR%\START.vbs" echo ScriptDir = FSO.GetParentFolderName^(WScript.ScriptFullName^)
>> "%INSTALL_DIR%\START.vbs" echo BatPath = ScriptDir ^& "\START.bat"
>> "%INSTALL_DIR%\START.vbs" echo If Not FSO.FileExists^(BatPath^) Then
>> "%INSTALL_DIR%\START.vbs" echo     MsgBox "Tired Market launcher not found: " ^& BatPath, vbExclamation, "Tired Market"
>> "%INSTALL_DIR%\START.vbs" echo     WScript.Quit 1
>> "%INSTALL_DIR%\START.vbs" echo End If
>> "%INSTALL_DIR%\START.vbs" echo WshShell.CurrentDirectory = ScriptDir
>> "%INSTALL_DIR%\START.vbs" echo WshShell.Run """" ^& BatPath ^& """", 0, False
>> "%INSTALL_DIR%\START.vbs" echo Set WshShell = Nothing
>> "%INSTALL_DIR%\START.vbs" echo Set FSO = Nothing
if not exist "%INSTALL_DIR%\START.vbs" (
    echo.
    echo ERROR: Could not write START.vbs to %INSTALL_DIR%.
    echo Check that you have write permission to that folder.
    echo.
    pause
    exit /b 1
)
echo START.vbs regenerated.

:have_vbs
echo [2/4] VBS launcher:    %INSTALL_DIR%\START.vbs

REM 3) Resolve the user's Desktop. PowerShell handles OneDrive redirection.
set "DESKTOP="
for /f "usebackq delims=" %%D in (`powershell -NoProfile -Command "[Environment]::GetFolderPath('Desktop')"`) do set "DESKTOP=%%D"
if not defined DESKTOP (
    if exist "%USERPROFILE%\Desktop" set "DESKTOP=%USERPROFILE%\Desktop"
)
if not defined DESKTOP (
    echo.
    echo ERROR: Could not locate your Desktop folder.
    pause
    exit /b 1
)

echo [3/4] Desktop folder:  %DESKTOP%

REM 4) Build the shortcut. Target = START.vbs directly; Windows uses its
REM    file association to run it through wscript.exe at click time.
REM    Paths flow via env vars so we don't have to escape quotes through cmd.
set "LNK_PATH=%DESKTOP%\Tired Market.lnk"
set "ICON_PATH=%INSTALL_DIR%\tired_market.ico"
set "VBS_PATH=%INSTALL_DIR%\START.vbs"
set "TM_DESC=Tired Market - AI-driven stock analysis"

echo [4/4] Writing shortcut: %LNK_PATH%
echo.

powershell -NoProfile -ExecutionPolicy Bypass -Command "$ws=New-Object -ComObject WScript.Shell; $lnk=$ws.CreateShortcut($env:LNK_PATH); $lnk.TargetPath=$env:VBS_PATH; $lnk.Arguments=''; $lnk.WorkingDirectory=$env:INSTALL_DIR; $lnk.Description=$env:TM_DESC; if (Test-Path $env:ICON_PATH) { $lnk.IconLocation=$env:ICON_PATH }; $lnk.WindowStyle=1; $lnk.Save(); $v=$ws.CreateShortcut($env:LNK_PATH); Write-Host ('  Target:    ' + $v.TargetPath); Write-Host ('  Arguments: ' + $v.Arguments); Write-Host ('  WorkDir:   ' + $v.WorkingDirectory); Write-Host ('  Icon:      ' + $v.IconLocation)"

if errorlevel 1 (
    echo.
    echo Shortcut creation FAILED. The PowerShell error is shown above.
    echo If your install dir is somewhere protected, try right-clicking
    echo this .bat and choosing "Run as administrator".
    pause
    exit /b 1
)

if not exist "%LNK_PATH%" (
    echo.
    echo PowerShell ran without an error but the shortcut wasn't created.
    echo Check that you have write permission to your Desktop folder.
    pause
    exit /b 1
)

echo.
echo ============================================================
echo   Done. "Tired Market" is on your desktop.
echo ============================================================
echo.
echo Look at your desktop now - you should see the Tired Market icon.
echo Double-click it to launch the app (no console flash).
echo.
echo Want it on the taskbar too?
echo   Right-click the desktop icon -^> "Pin to taskbar"
echo.
echo Want it in the Start menu?
echo   Right-click the desktop icon -^> "Pin to Start"
echo.
echo Re-run this installer any time to refresh the shortcut (e.g. after
echo Python is upgraded or the install moves).
echo.
pause
exit /b 0
